{
  "title": "Schema",
  "type": "object",
  "properties": {
    "components": {
      "title": "Components",
      "type": "array",
      "items": {
        "anyOf": [
          {
            "$ref": "#/definitions/AsynString"
          },
          {
            "$ref": "#/definitions/AsynFloat64"
          }
        ]
      }
    }
  },
  "required": [
    "components"
  ],
  "definitions": {
    "AsynString": {
      "title": "AsynString",
      "description": "Asyn String Parameter and records",
      "type": "object",
      "properties": {
        "type": {
          "title": "Type",
          "const": "AsynString",
          "type": "string"
        },
        "name": {
          "title": "Name",
          "description": "Parameter, record and device field name",
          "type": "string"
        },
        "desc": {
          "title": "Desc",
          "description": "Record and device field description",
          "type": "string"
        },
        "role": {
          "title": "Role",
          "description": "The role of the created device field",
          "default": "SETTING",
          "enum": [
            "READ",
            "WRITE",
            "SETTING",
            "POSITIONER"
          ],
          "type": "string"
        },
        "autosave": {
          "title": "Autosave",
          "description": "Record fields that should be autosaved",
          "default": [],
          "type": "array",
          "items": {
            "type": "string"
          }
        }
      },
      "required": [
        "type",
        "name",
        "desc"
      ]
    },
    "AsynFloat64": {
      "title": "AsynFloat64",
      "description": "Asyn Float64 Parameter and records",
      "type": "object",
      "properties": {
        "type": {
          "title": "Type",
          "const": "AsynFloat64",
          "type": "string"
        },
        "name": {
          "title": "Name",
          "description": "Parameter, record and device field name",
          "type": "string"
        },
        "desc": {
          "title": "Desc",
          "description": "Record and device field description",
          "type": "string"
        },
        "role": {
          "title": "Role",
          "description": "The role of the created device field",
          "default": "SETTING",
          "enum": [
            "READ",
            "WRITE",
            "SETTING",
            "POSITIONER"
          ],
          "type": "string"
        },
        "autosave": {
          "title": "Autosave",
          "description": "Record fields that should be autosaved",
          "default": [],
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "prec": {
          "title": "Prec",
          "description": "Record precision",
          "default": 3,
          "type": "integer"
        },
        "egu": {
          "title": "Egu",
          "description": "Record engineering units",
          "default": "",
          "type": "string"
        }
      },
      "required": [
        "type",
        "name",
        "desc"
      ]
    }
  }
}